### ISSUE TITLE
Introduce configuration to oxd-to-http app

### ISSUE THREAD

**Issue by yuriyz** [GluuFederation/oxd-to-http#1]
We have to introduce configuration and instead of using hardcodes like here :
https://github.com/GluuFederation/oxd-to-http/blob/master/src/main/java/org/gluu/oxd/Configuration.java#L4

**Comment by snehaldkshah** [comment]
I have created properties file  and reading all the details from it even for test cases as well.

**Comment by yuriyz** [comment]
please use standard dropwizard configuration file instead of reading properties manually

See https://github.com/GluuFederation/oxd-to-http/blob/master/src/main/java/org/gluu/oxd/OxdToHttpConfiguration.java

**Comment by snehaldkshah** [comment]
I have completed this using dropwizard yml file..
