### ISSUE TITLE
Add `Authorization` header to all commands and pass `access_token` to oxd

### ISSUE THREAD

**Issue by yuriyz** [GluuFederation/oxd-to-http#8]
oxd http must require 'access_token' in `Authorization` header to force security flow.

```
POST /get-authorization-url
Authorization: Bearer adtfgr-flgt-rlfly-qwer-bckjf
{
   "oxd_id": "<oxd_id>"
   // other parameters
}
```
And then call oxd-java as 
```
Command command = // command
command.accessToken(accessTokenFromHeader);
```

Note : accessToken method will be added to oxd-java this week.

**Comment by yuriyz** [comment]
if access_token is blank than return 403 Forbidden http code, do not call oxd at all in this case

**Comment by snehaldkshah** [comment]
I already completed this
